Rollback of commit 99de0d07574f808fee36826289cb1f5c83e3b3e0.
*** Reason for rollback ***

Makes blaze unable to build //third_party/stl
IllegalArgumentException: complex.h.processed
  at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
  at com.google.devtools.build.lib.util.Preconditions.checkArgument(Preconditions.java:38)
  at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.addObjectFile(CppLinkActionBuilder.java:831)

NOT a clean rollback; conflict in one file (CppCompilationContext.java).
So this also partially rolls back commit 603b540bbcd7414cd3e2c0b92c1c8985b035e41b (just the change in that file).

*** Original change description ***

Cleanup: store non-code inputs to link actions separately.

--
MOS_MIGRATED_REVID=129798636