Fix {new_,}git_repository after shutdown.
Previously, after a server shutdown they would fail because the
repository already exists. This change fixes that and avoids
re-downloading if the local repository is already the correct version
and unmodified.

An example of the error before:
$ bazel fetch ...
.......
INFO: Loading package: tools/cpp
java.lang.RuntimeException: Unrecoverable error while evaluating node 'GIT_CLONE:file:///tmp/gtest-1.7.0 -> /home/brian/.cache/bazel/_bazel_brian/46af2c6e62e13aca9af015360f8fb1da/external/gtest_repo (091e69312f2c133860e71e6b01118c1f5a8c943d) submodules: false' (requested by nodes 'NEW_GIT_REPOSITORY:@gtest_repo')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:745)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$1.run(AbstractQueueVisitor.java:346)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Destination path "gtest_repo" already exists and is not an empty directory
	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:152)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:132)
	at com.google.devtools.build.lib.bazel.repository.GitCloneFunction.compute(GitCloneFunction.java:68)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:709)
	... 4 more

--
Change-Id: Ifca46302537248106740941b70bc5bd11fa1eeb1
Reviewed-on: https://bazel-review.googlesource.com/#/c/1650
MOS_MIGRATED_REVID=101045419